import type { Prisma } from '@prisma/client'
import { prisma } from '@/lib/db'
import { generateAndSaveInsight } from './insight-generation.service'

/**
 * Feature spec 1.6 — US-15. City Recommendations are a HYBRID: a
 * deterministic composite score per city (this file's pure `scoreCities`
 * function — reproducible, unit-tested) plus an AI narrative summary
 * generated alongside it. The score itself must never come from the AI
 * provider (same determinism rule as the Readiness Score, DECISIONS.md
 * D-04) — only the prose explaining it does.
 */

export interface CityScoringWeights {
  populationTier: number
  distributionMaturity: number
}

export const DEFAULT_CITY_WEIGHTS: CityScoringWeights = {
  populationTier: 0.5,
  distributionMaturity: 0.5,
}

interface CityInput {
  id: string
  name: string
  tier: string | null
  distributionMaturity: unknown
}

export interface CityScoreResult {
  cityId: string
  name: string
  compositeScore: number
  drivers: { populationTier: number; distributionMaturity: number }
  dataCompleteness: 'complete' | 'partial' | 'insufficient_data'
}

const TIER_SCORES: Record<string, number> = { tier1: 100, tier2: 65, tier3: 35 }
const MATURITY_LEVEL_SCORES: Record<string, number> = { high: 100, medium: 60, low: 30 }

function scoreDistributionMaturity(raw: unknown): { score: number; hasData: boolean } {
  if (!raw || typeof raw !== 'object') return { score: 0, hasData: false }
  const levels = Object.values(raw as Record<string, unknown>).filter(
    (v): v is string => typeof v === 'string' && v in MATURITY_LEVEL_SCORES,
  )
  if (levels.length === 0) return { score: 0, hasData: false }
  const avg = levels.reduce((sum, l) => sum + MATURITY_LEVEL_SCORES[l], 0) / levels.length
  return { score: avg, hasData: true }
}

/** Pure, deterministic — same cities+weights always produce the same ranked result. */
export function scoreCities(cities: CityInput[], weights: CityScoringWeights): CityScoreResult[] {
  const weightSum = weights.populationTier + weights.distributionMaturity
  const normalized =
    weightSum > 0 ? weights : { populationTier: 0.5, distributionMaturity: 0.5 }

  const results = cities.map((city) => {
    const tierScore = city.tier ? (TIER_SCORES[city.tier] ?? 0) : 0
    const maturity = scoreDistributionMaturity(city.distributionMaturity)

    const compositeScore = Math.round(
      (normalized.populationTier * tierScore + normalized.distributionMaturity * maturity.score) / weightSum,
    )

    const dataCompleteness: CityScoreResult['dataCompleteness'] =
      city.tier && maturity.hasData ? 'complete' : city.tier || maturity.hasData ? 'partial' : 'insufficient_data'

    return {
      cityId: city.id,
      name: city.name,
      compositeScore,
      drivers: { populationTier: tierScore, distributionMaturity: maturity.score },
      dataCompleteness,
    }
  })

  return results.sort((a, b) => b.compositeScore - a.compositeScore)
}

export async function generateCityRecommendations(
  organizationId: string,
  weights: CityScoringWeights = DEFAULT_CITY_WEIGHTS,
  requestedByUserId?: string,
) {
  const [brandProfile, cities] = await Promise.all([
    prisma.brandProfile.findUnique({ where: { organizationId } }),
    prisma.city.findMany(),
  ])

  const rankedCities = scoreCities(cities, weights)
  const tags = ['general', 'distribution', brandProfile?.category ?? 'general']

  const insight = await generateAndSaveInsight({
    organizationId,
    category: 'city_recommendation',
    inputParams: { weights, category: brandProfile?.category },
    tags,
    requestedByUserId,
  })

  // The AI narrative is generic context; the ranked list itself is the
  // deterministic part and is merged into structuredOutput here (not
  // generated by the AI provider) — see the module-level doc comment.
  return prisma.aiInsight.update({
    where: { id: insight.id },
    data: {
      structuredOutput: {
        ...(insight.structuredOutput as object),
        rankedCities,
      } as unknown as Prisma.InputJsonValue,
    },
    include: { sources: true },
  })
}
